common: &common
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password:
  min_messages: WARNING

development: &development
  <<: *common
  database: mikeodmark_dev

test: &test
  <<: *common
  database: mikeodmark_test

production: &production
  <<: *common
  database: mikeodmark_prod
